package software.hacker_E303.pigeon_core.actions;

import net.minecraft.world.entity.player.Player;

/**
 * Provides generation/initialization events for entities.
 */
public interface IGeneration {

    /**
     * Called when an entity is initialized, spawned, or summoned.
     */
    default boolean generationEvent(GenerationType type) {
        return false;
    }

    /**
     * Called when an entity is generated by a player spawner (turrets).
     */
    default boolean generationEvent(Player player) {
        return false;
    }

    /**
     * Generation event types.
     */
    public enum GenerationType {
        INIT,
        SPAWN,
        SUMMON
    }
}